// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppMovieProject.Models;

public partial class Actor
{
    public int ActorId { get; set; }

    public string ActorName { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}