// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppMovieProject.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Title { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public decimal? ImdbRating { get; set; }

    public string ImageUrl { get; set; }

    public bool Watched { get; set; }

    public DateOnly? WatchedDate { get; set; }

    public int? PlatformId { get; set; }

    public virtual StreamingPlatform Platform { get; set; }

    public virtual ICollection<Actor> Actors { get; set; } = new List<Actor>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

}